/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type Navigation = {
  _id: string;
  _type: "navigation";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  href?: string;
  icon?: string;
  linkType?: "internal" | "external";
  order?: number;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  siteTitle?: string;
  siteDescription?: string;
  siteLogo?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  showBlog?: boolean;
  showServices?: boolean;
  showTestimonials?: boolean;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Contact = {
  _id: string;
  _type: "contact";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  email?: string;
  subject?: string;
  message?: string;
  submittedAt?: string;
  status?: "new" | "archived";
  notes?: string;
};

export type Blog = {
  _id: string;
  _type: "blog";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  excerpt?: string;
  category?: string;
  tags?: Array<string>;
  publishedAt?: string;
  readTime?: number;
  featuredImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  content?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Achievement = {
  _id: string;
  _type: "achievement";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  type?: "award" | "hackathon" | "publication" | "speaking" | "open-source" | "milestone" | "recognition" | "other";
  issuer?: string;
  date?: string;
  description?: string;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  url?: string;
  featured?: boolean;
  order?: number;
};

export type Certification = {
  _id: string;
  _type: "certification";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  issuer?: string;
  issueDate?: string;
  expiryDate?: string;
  credentialId?: string;
  credentialUrl?: string;
  logo?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  description?: string;
  skills?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "skill";
  }>;
  order?: number;
};

export type Testimonial = {
  _id: string;
  _type: "testimonial";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  position?: string;
  company?: string;
  testimonial?: string;
  rating?: number;
  date?: string;
  avatar?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  companyLogo?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  linkedinUrl?: string;
  featured?: boolean;
  order?: number;
};

export type Education = {
  _id: string;
  _type: "education";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  institution?: string;
  degree?: string;
  fieldOfStudy?: string;
  startDate?: string;
  endDate?: string;
  current?: boolean;
  gpa?: string;
  description?: string;
  achievements?: Array<string>;
  logo?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  website?: string;
  order?: number;
};

export type Experience = {
  _id: string;
  _type: "experience";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  company?: string;
  position?: string;
  employmentType?: "full-time" | "part-time" | "contract" | "freelance" | "internship";
  location?: string;
  startDate?: string;
  endDate?: string;
  tenure?: "current" | "past";
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  responsibilities?: Array<string>;
  achievements?: Array<string>;
  technologies?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "skill";
  }>;
  companyLogo?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  companyWebsite?: string;
  order?: number;
};

export type Skill = {
  _id: string;
  _type: "skill";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  category?: "frontend" | "backend" | "ai-ml" | "devops" | "database" | "mobile" | "cloud" | "testing" | "design" | "tools" | "soft-skills" | "other";
  proficiency?: "beginner" | "intermediate" | "advanced" | "expert";
  percentage?: number;
  yearsOfExperience?: number;
  tone?: "neutral" | "accent" | "highlight" | "muted";
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  tagline?: string;
  coverImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  technologies?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "skill";
  }>;
  category?: "web-app" | "mobile-app" | "ai-ml" | "api-backend" | "devops" | "open-source" | "cli-tool" | "desktop-app" | "browser-extension" | "game" | "other";
  liveUrl?: string;
  githubUrl?: string;
  visibility?: "featured" | "standard";
  order?: number;
};

export type Profile = {
  _id: string;
  _type: "profile";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  firstName?: string;
  lastName?: string;
  headline?: string;
  headlineStaticText?: string;
  headlineAnimatedWords?: Array<string>;
  headlineAnimationDuration?: number;
  shortBio?: string;
  fullBio?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  profileImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  email?: string;
  phone?: string;
  location?: string;
  availability?: "available" | "open" | "unavailable";
  socialLinks?: {
    github?: string;
    linkedin?: string;
    twitter?: string;
    website?: string;
    medium?: string;
    devto?: string;
    youtube?: string;
    stackoverflow?: string;
  };
  yearsOfExperience?: number;
  stats?: Array<{
    label?: string;
    value?: string;
    _key: string;
  }>;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes = Navigation | SiteSettings | SanityImageCrop | SanityImageHotspot | Contact | Blog | Slug | Achievement | Certification | Testimonial | Education | Experience | Skill | Project | Profile | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageMetadata | SanityFileAsset | SanityAssetSourceData | SanityImageAsset | Geopoint;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./src/components/FloatingDock.tsx
// Variable: FLOATING_NAV_QUERY
// Query: *[_type == "navigation"] | order(order asc){ _id, title, href, isExternal, order }
export type FLOATING_NAV_QUERYResult = Array<{
  _id: string;
  title: string | null;
  href: string | null;
  isExternal: null;
  order: number | null;
}>;

// Source: ./src/components/sections/AboutSection.tsx
// Variable: ABOUT_QUERY
// Query: *[_id == "singleton-profile"][0]{  firstName,  lastName,  fullBio,  yearsOfExperience,  stats,  email,  phone,  location}
export type ABOUT_QUERYResult = {
  firstName: null;
  lastName: null;
  fullBio: null;
  yearsOfExperience: null;
  stats: null;
  email: null;
  phone: null;
  location: null;
} | {
  firstName: null;
  lastName: null;
  fullBio: null;
  yearsOfExperience: number | null;
  stats: null;
  email: null;
  phone: null;
  location: null;
} | {
  firstName: null;
  lastName: null;
  fullBio: null;
  yearsOfExperience: null;
  stats: null;
  email: null;
  phone: null;
  location: string | null;
} | {
  firstName: null;
  lastName: null;
  fullBio: null;
  yearsOfExperience: null;
  stats: null;
  email: string | null;
  phone: null;
  location: null;
} | {
  firstName: string | null;
  lastName: string | null;
  fullBio: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  yearsOfExperience: number | null;
  stats: Array<{
    label?: string;
    value?: string;
    _key: string;
  }> | null;
  email: string | null;
  phone: string | null;
  location: string | null;
} | null;

// Source: ./src/components/sections/AchievementsSection.tsx
// Variable: ACHIEVEMENTS_SECTION_QUERY
// Query: *[_type == "achievement"] | order(date desc){    _id, title, description, date, type, featured  }
export type ACHIEVEMENTS_SECTION_QUERYResult = Array<{
  _id: string;
  title: string | null;
  description: string | null;
  date: string | null;
  type: "award" | "hackathon" | "milestone" | "open-source" | "other" | "publication" | "recognition" | "speaking" | null;
  featured: boolean | null;
}>;

// Source: ./src/components/sections/BlogSection.tsx
// Variable: BLOG_SECTION_QUERY
// Query: *[_type == "blog"] | order(publishedAt desc)[0...6]{    _id, title, slug, excerpt, publishedAt, readTime, category, featuredImage  }
export type BLOG_SECTION_QUERYResult = Array<{
  _id: string;
  title: string | null;
  slug: Slug | null;
  excerpt: string | null;
  publishedAt: string | null;
  readTime: number | null;
  category: string | null;
  featuredImage: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
}>;

// Source: ./src/components/sections/CertificationsSection.tsx
// Variable: CERTS_SECTION_QUERY
// Query: *[_type == "certification"] | order(issueDate desc){    _id, name, issuer, issueDate, credentialId, credentialUrl, logo  }
export type CERTS_SECTION_QUERYResult = Array<{
  _id: string;
  name: string | null;
  issuer: string | null;
  issueDate: string | null;
  credentialId: string | null;
  credentialUrl: string | null;
  logo: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
}>;

// Source: ./src/components/sections/ContactSection.tsx
// Variable: CONTACT_QUERY
// Query: *[_id == "singleton-profile"][0]{ email, phone, location, socialLinks }
export type CONTACT_QUERYResult = {
  email: null;
  phone: null;
  location: null;
  socialLinks: null;
} | {
  email: null;
  phone: null;
  location: string | null;
  socialLinks: null;
} | {
  email: string | null;
  phone: null;
  location: null;
  socialLinks: null;
} | {
  email: string | null;
  phone: string | null;
  location: string | null;
  socialLinks: {
    github?: string;
    linkedin?: string;
    twitter?: string;
    website?: string;
    medium?: string;
    devto?: string;
    youtube?: string;
    stackoverflow?: string;
  } | null;
} | null;

// Source: ./src/components/sections/EducationSection.tsx
// Variable: EDUCATION_SECTION_QUERY
// Query: *[_type == "education"] | order(startDate desc){    _id, institution, degree, fieldOfStudy, startDate, endDate, current, description, gpa  }
export type EDUCATION_SECTION_QUERYResult = Array<{
  _id: string;
  institution: string | null;
  degree: string | null;
  fieldOfStudy: string | null;
  startDate: string | null;
  endDate: string | null;
  current: boolean | null;
  description: string | null;
  gpa: string | null;
}>;

// Source: ./src/components/sections/ServicesSection.tsx
// Variable: SERVICES_SECTION_QUERY
// Query: *[_type == "service"] | order(order asc){    _id, title, description, features, price, priceType, featured, icon, order  }
export type SERVICES_SECTION_QUERYResult = Array<never>;

// Source: ./src/components/sections/TestimonialsSection.tsx
// Variable: TESTIMONIALS_SECTION_QUERY
// Query: *[_type == "testimonial"] | order(order asc){ _id, testimonial, name, position, avatar }
export type TESTIMONIALS_SECTION_QUERYResult = Array<{
  _id: string;
  testimonial: string | null;
  name: string | null;
  position: string | null;
  avatar: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
}>;

// Source: ./src/sanity/lib/queries.ts
// Variable: PROFILE_QUERY
// Query: coalesce(  *[_type == "profile" && _id == "singleton-profile"][0],  *[_type == "profile"][0]){  _id,  firstName,  lastName,  headline,  headlineStaticText,  headlineAnimatedWords,  headlineAnimationDuration,  shortBio,  fullBio,  profileImage,  email,  phone,  location,  availability,  socialLinks{    github,    linkedin,    twitter,    website,    medium,    devto,    youtube,    stackoverflow  },  yearsOfExperience,  stats[]{    label,    value  }}
export type PROFILE_QUERYResult = {
  _id: string;
  firstName: string | null;
  lastName: string | null;
  headline: string | null;
  headlineStaticText: string | null;
  headlineAnimatedWords: Array<string> | null;
  headlineAnimationDuration: number | null;
  shortBio: string | null;
  fullBio: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  profileImage: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  email: string | null;
  phone: string | null;
  location: string | null;
  availability: "available" | "open" | "unavailable" | null;
  socialLinks: {
    github: string | null;
    linkedin: string | null;
    twitter: string | null;
    website: string | null;
    medium: string | null;
    devto: string | null;
    youtube: string | null;
    stackoverflow: string | null;
  } | null;
  yearsOfExperience: number | null;
  stats: Array<{
    label: string | null;
    value: string | null;
  }> | null;
} | {
  _id: "singleton-profile";
  firstName: string | null;
  lastName: string | null;
  headline: string | null;
  headlineStaticText: string | null;
  headlineAnimatedWords: Array<string> | null;
  headlineAnimationDuration: number | null;
  shortBio: string | null;
  fullBio: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  profileImage: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  email: string | null;
  phone: string | null;
  location: string | null;
  availability: "available" | "open" | "unavailable" | null;
  socialLinks: {
    github: string | null;
    linkedin: string | null;
    twitter: string | null;
    website: string | null;
    medium: string | null;
    devto: string | null;
    youtube: string | null;
    stackoverflow: string | null;
  } | null;
  yearsOfExperience: number | null;
  stats: Array<{
    label: string | null;
    value: string | null;
  }> | null;
} | null;
// Variable: SITE_SETTINGS_QUERY
// Query: coalesce(  *[_type == "siteSettings" && _id == "singleton-siteSettings"][0],  *[_type == "siteSettings"][0]){  _id,  siteTitle,  siteDescription,  siteKeywords,  siteLogo,  favicon,  ogImage,  primaryColor,  secondaryColor,  accentColor,  ctaText,  ctaUrl,  heroHeadline,  heroSubheadline,  heroBackground,  showBlog,  showServices,  showTestimonials,  googleAnalyticsId,  facebookPixelId,  twitterHandle,  footer{    text,    copyrightText,    links[]{ title, url }  },  maintenanceMode,  maintenanceMessage}
export type SITE_SETTINGS_QUERYResult = {
  _id: string;
  siteTitle: string | null;
  siteDescription: string | null;
  siteKeywords: null;
  siteLogo: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  favicon: null;
  ogImage: null;
  primaryColor: null;
  secondaryColor: null;
  accentColor: null;
  ctaText: null;
  ctaUrl: null;
  heroHeadline: null;
  heroSubheadline: null;
  heroBackground: null;
  showBlog: boolean | null;
  showServices: boolean | null;
  showTestimonials: boolean | null;
  googleAnalyticsId: null;
  facebookPixelId: null;
  twitterHandle: null;
  footer: null;
  maintenanceMode: null;
  maintenanceMessage: null;
} | {
  _id: "singleton-siteSettings";
  siteTitle: string | null;
  siteDescription: string | null;
  siteKeywords: null;
  siteLogo: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  favicon: null;
  ogImage: null;
  primaryColor: null;
  secondaryColor: null;
  accentColor: null;
  ctaText: null;
  ctaUrl: null;
  heroHeadline: null;
  heroSubheadline: null;
  heroBackground: null;
  showBlog: boolean | null;
  showServices: boolean | null;
  showTestimonials: boolean | null;
  googleAnalyticsId: null;
  facebookPixelId: null;
  twitterHandle: null;
  footer: null;
  maintenanceMode: null;
  maintenanceMessage: null;
} | null;
// Variable: NAVIGATION_QUERY
// Query: *[_type == "navigation"] | order(order asc){  _id,  title,  href,  icon,  "isExternal": select(    isExternal == true => true,    linkType == "external" => true,    false  ),  order}
export type NAVIGATION_QUERYResult = Array<{
  _id: string;
  title: string | null;
  href: string | null;
  icon: string | null;
  isExternal: false | true;
  order: number | null;
}>;
// Variable: PROJECTS_QUERY
// Query: *[_type == "project"] | order(featured desc, order asc){  _id,  title,  slug{ current },  tagline,  coverImage,  technologies[]->{    _id,    name,    category,    proficiency,    percentage,    yearsOfExperience,    color  },  category,  liveUrl,  githubUrl,  featured,  order}
export type PROJECTS_QUERYResult = Array<{
  _id: string;
  title: string | null;
  slug: {
    current: string | null;
  } | null;
  tagline: string | null;
  coverImage: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  technologies: Array<{
    _id: string;
    name: string | null;
    category: "ai-ml" | "backend" | "cloud" | "database" | "design" | "devops" | "frontend" | "mobile" | "other" | "soft-skills" | "testing" | "tools" | null;
    proficiency: "advanced" | "beginner" | "expert" | "intermediate" | null;
    percentage: number | null;
    yearsOfExperience: number | null;
    color: null;
  }> | null;
  category: "ai-ml" | "api-backend" | "browser-extension" | "cli-tool" | "desktop-app" | "devops" | "game" | "mobile-app" | "open-source" | "other" | "web-app" | null;
  liveUrl: string | null;
  githubUrl: string | null;
  featured: null;
  order: number | null;
}>;
// Variable: SKILLS_QUERY
// Query: *[_type == "skill"] | order(category asc, name asc){  _id,  name,  category,  proficiency,  percentage,  yearsOfExperience,  color}
export type SKILLS_QUERYResult = Array<{
  _id: string;
  name: string | null;
  category: "ai-ml" | "backend" | "cloud" | "database" | "design" | "devops" | "frontend" | "mobile" | "other" | "soft-skills" | "testing" | "tools" | null;
  proficiency: "advanced" | "beginner" | "expert" | "intermediate" | null;
  percentage: number | null;
  yearsOfExperience: number | null;
  color: null;
}>;
// Variable: CHAT_PROFILE_QUERY
// Query: *[_id == "singleton-profile"][0]{    firstName, lastName, headline  }
export type CHAT_PROFILE_QUERYResult = {
  firstName: null;
  lastName: null;
  headline: null;
} | {
  firstName: string | null;
  lastName: string | null;
  headline: string | null;
} | null;
// Variable: EXPERIENCE_QUERY
// Query: *[_type == "experience"] | order(order asc, startDate desc){  _id,  company,  position,  employmentType,  location,  startDate,  endDate,  current,  responsibilities[],  achievements[],  technologies[]->{    _id,    name,    category,    proficiency,    percentage,    yearsOfExperience,    color  },  companyLogo,  companyWebsite,  order}
export type EXPERIENCE_QUERYResult = Array<{
  _id: string;
  company: string | null;
  position: string | null;
  employmentType: "contract" | "freelance" | "full-time" | "internship" | "part-time" | null;
  location: string | null;
  startDate: string | null;
  endDate: string | null;
  current: null;
  responsibilities: Array<string> | null;
  achievements: Array<string> | null;
  technologies: Array<{
    _id: string;
    name: string | null;
    category: "ai-ml" | "backend" | "cloud" | "database" | "design" | "devops" | "frontend" | "mobile" | "other" | "soft-skills" | "testing" | "tools" | null;
    proficiency: "advanced" | "beginner" | "expert" | "intermediate" | null;
    percentage: number | null;
    yearsOfExperience: number | null;
    color: null;
  }> | null;
  companyLogo: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  companyWebsite: string | null;
  order: number | null;
}>;
// Variable: EDUCATION_QUERY
// Query: *[_type == "education"] | order(startDate desc){    _id, institution, degree, fieldOfStudy, startDate, endDate, current, description, gpa  }
export type EDUCATION_QUERYResult = Array<{
  _id: string;
  institution: string | null;
  degree: string | null;
  fieldOfStudy: string | null;
  startDate: string | null;
  endDate: string | null;
  current: boolean | null;
  description: string | null;
  gpa: string | null;
}>;
// Variable: TESTIMONIALS_QUERY
// Query: *[_type == "testimonial"] | order(order asc){    _id, testimonial, name, position, avatar, order  }
export type TESTIMONIALS_QUERYResult = Array<{
  _id: string;
  testimonial: string | null;
  name: string | null;
  position: string | null;
  avatar: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  order: number | null;
}>;
// Variable: CERTIFICATIONS_QUERY
// Query: *[_type == "certification"] | order(issueDate desc){    _id, name, issuer, issueDate, credentialId, credentialUrl, logo  }
export type CERTIFICATIONS_QUERYResult = Array<{
  _id: string;
  name: string | null;
  issuer: string | null;
  issueDate: string | null;
  credentialId: string | null;
  credentialUrl: string | null;
  logo: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
}>;
// Variable: ACHIEVEMENTS_QUERY
// Query: *[_type == "achievement"] | order(date desc){    _id, title, description, date, type, featured  }
export type ACHIEVEMENTS_QUERYResult = Array<{
  _id: string;
  title: string | null;
  description: string | null;
  date: string | null;
  type: "award" | "hackathon" | "milestone" | "open-source" | "other" | "publication" | "recognition" | "speaking" | null;
  featured: boolean | null;
}>;
// Variable: SERVICES_QUERY
// Query: *[_type == "service"] | order(order asc){    _id, title, description, features, price, priceType, featured, icon, order  }
export type SERVICES_QUERYResult = Array<never>;
// Variable: BLOG_QUERY
// Query: *[_type == "blog"] | order(publishedAt desc)[0...6]{    _id, title, slug, excerpt, publishedAt, readTime, category, featuredImage  }
export type BLOG_QUERYResult = Array<{
  _id: string;
  title: string | null;
  slug: Slug | null;
  excerpt: string | null;
  publishedAt: string | null;
  readTime: number | null;
  category: string | null;
  featuredImage: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "\n  *[_type == \"navigation\"] | order(order asc){ _id, title, href, isExternal, order }\n": FLOATING_NAV_QUERYResult;
    "*[_id == \"singleton-profile\"][0]{\n  firstName,\n  lastName,\n  fullBio,\n  yearsOfExperience,\n  stats,\n  email,\n  phone,\n  location\n}": ABOUT_QUERYResult;
    "\n  *[_type == \"achievement\"] | order(date desc){\n    _id, title, description, date, type, featured\n  }\n": ACHIEVEMENTS_SECTION_QUERYResult | ACHIEVEMENTS_QUERYResult;
    "\n  *[_type == \"blog\"] | order(publishedAt desc)[0...6]{\n    _id, title, slug, excerpt, publishedAt, readTime, category, featuredImage\n  }\n": BLOG_SECTION_QUERYResult | BLOG_QUERYResult;
    "\n  *[_type == \"certification\"] | order(issueDate desc){\n    _id, name, issuer, issueDate, credentialId, credentialUrl, logo\n  }\n": CERTS_SECTION_QUERYResult | CERTIFICATIONS_QUERYResult;
    "\n  *[_id == \"singleton-profile\"][0]{ email, phone, location, socialLinks }\n": CONTACT_QUERYResult;
    "\n  *[_type == \"education\"] | order(startDate desc){\n    _id, institution, degree, fieldOfStudy, startDate, endDate, current, description, gpa\n  }\n": EDUCATION_SECTION_QUERYResult | EDUCATION_QUERYResult;
    "\n  *[_type == \"service\"] | order(order asc){\n    _id, title, description, features, price, priceType, featured, icon, order\n  }\n": SERVICES_SECTION_QUERYResult | SERVICES_QUERYResult;
    "\n  *[_type == \"testimonial\"] | order(order asc){ _id, testimonial, name, position, avatar }\n": TESTIMONIALS_SECTION_QUERYResult;
    "\ncoalesce(\n  *[_type == \"profile\" && _id == \"singleton-profile\"][0],\n  *[_type == \"profile\"][0]\n){\n  _id,\n  firstName,\n  lastName,\n  headline,\n  headlineStaticText,\n  headlineAnimatedWords,\n  headlineAnimationDuration,\n  shortBio,\n  fullBio,\n  profileImage,\n  email,\n  phone,\n  location,\n  availability,\n  socialLinks{\n    github,\n    linkedin,\n    twitter,\n    website,\n    medium,\n    devto,\n    youtube,\n    stackoverflow\n  },\n  yearsOfExperience,\n  stats[]{\n    label,\n    value\n  }\n}\n": PROFILE_QUERYResult;
    "\ncoalesce(\n  *[_type == \"siteSettings\" && _id == \"singleton-siteSettings\"][0],\n  *[_type == \"siteSettings\"][0]\n){\n  _id,\n  siteTitle,\n  siteDescription,\n  siteKeywords,\n  siteLogo,\n  favicon,\n  ogImage,\n  primaryColor,\n  secondaryColor,\n  accentColor,\n  ctaText,\n  ctaUrl,\n  heroHeadline,\n  heroSubheadline,\n  heroBackground,\n  showBlog,\n  showServices,\n  showTestimonials,\n  googleAnalyticsId,\n  facebookPixelId,\n  twitterHandle,\n  footer{\n    text,\n    copyrightText,\n    links[]{ title, url }\n  },\n  maintenanceMode,\n  maintenanceMessage\n}\n": SITE_SETTINGS_QUERYResult;
    "\n*[_type == \"navigation\"] | order(order asc){\n  _id,\n  title,\n  href,\n  icon,\n  \"isExternal\": select(\n    isExternal == true => true,\n    linkType == \"external\" => true,\n    false\n  ),\n  order\n}\n": NAVIGATION_QUERYResult;
    "\n*[_type == \"project\"] | order(featured desc, order asc){\n  _id,\n  title,\n  slug{ current },\n  tagline,\n  coverImage,\n  technologies[]->{\n    _id,\n    name,\n    category,\n    proficiency,\n    percentage,\n    yearsOfExperience,\n    color\n  },\n  category,\n  liveUrl,\n  githubUrl,\n  featured,\n  order\n}\n": PROJECTS_QUERYResult;
    "\n*[_type == \"skill\"] | order(category asc, name asc){\n  _id,\n  name,\n  category,\n  proficiency,\n  percentage,\n  yearsOfExperience,\n  color\n}\n": SKILLS_QUERYResult;
    "\n  *[_id == \"singleton-profile\"][0]{\n    firstName, lastName, headline\n  }\n": CHAT_PROFILE_QUERYResult;
    "\n*[_type == \"experience\"] | order(order asc, startDate desc){\n  _id,\n  company,\n  position,\n  employmentType,\n  location,\n  startDate,\n  endDate,\n  current,\n  responsibilities[],\n  achievements[],\n  technologies[]->{\n    _id,\n    name,\n    category,\n    proficiency,\n    percentage,\n    yearsOfExperience,\n    color\n  },\n  companyLogo,\n  companyWebsite,\n  order\n}\n": EXPERIENCE_QUERYResult;
    "\n  *[_type == \"testimonial\"] | order(order asc){\n    _id, testimonial, name, position, avatar, order\n  }\n": TESTIMONIALS_QUERYResult;
  }
}
