/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type Navigation = {
  _id: string;
  _type: "navigation";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  href?: string;
  icon?: string;
  isExternal?: boolean;
  linkType?: "internal" | "external";
  order?: number;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  siteTitle?: string;
  siteDescription?: string;
  siteLogo?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  showBlog?: boolean;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Blog = {
  _id: string;
  _type: "blog";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  excerpt?: string;
  externalUrl?: string;
  category?: string;
  tags?: Array<string>;
  publishedAt?: string;
  readTime?: number;
  featuredImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Achievement = {
  _id: string;
  _type: "achievement";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  type?: "award" | "experience" | "leadership" | "entrepreneurship" | "sports" | "hackathon" | "publication" | "speaking" | "open-source" | "milestone" | "recognition" | "other";
  issuer?: string;
  date?: string;
  description?: string;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  url?: string;
  featured?: boolean;
  order?: number;
};

export type Certification = {
  _id: string;
  _type: "certification";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  issuer?: string;
  issueDate?: string;
  expiryDate?: string;
  credentialId?: string;
  credentialUrl?: string;
  logo?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  description?: string;
  skills?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "skill";
  }>;
  order?: number;
};

export type Education = {
  _id: string;
  _type: "education";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  institution?: string;
  degree?: string;
  fieldOfStudy?: string;
  startDate?: string;
  endDate?: string;
  current?: boolean;
  gpa?: string;
  description?: string;
  achievements?: Array<string>;
  logo?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  website?: string;
  order?: number;
};

export type Experience = {
  _id: string;
  _type: "experience";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  company?: string;
  position?: string;
  employmentType?: "full-time" | "part-time" | "contract" | "freelance" | "internship";
  location?: string;
  startDate?: string;
  endDate?: string;
  tenure?: "current" | "past";
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  responsibilities?: Array<string>;
  achievements?: Array<string>;
  technologies?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "skill";
  }>;
  companyLogo?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  companyWebsite?: string;
  order?: number;
};

export type Skill = {
  _id: string;
  _type: "skill";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  category?: "frontend" | "backend" | "ai-ml" | "devops" | "database" | "mobile" | "cloud" | "testing" | "design" | "tools" | "soft-skills" | "other";
  proficiency?: "beginner" | "intermediate" | "advanced" | "expert";
  percentage?: number;
  yearsOfExperience?: number;
  tone?: "neutral" | "accent" | "highlight" | "muted";
  color?: "violet" | "cyan" | "emerald" | "sky" | "pink" | "amber" | "orange" | "slate";
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  tagline?: string;
  summary?: string;
  coverImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  technologies?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "skill";
  }>;
  category?: "web-app" | "mobile-app" | "ai-ml" | "api-backend" | "devops" | "open-source" | "cli-tool" | "desktop-app" | "browser-extension" | "game" | "other";
  liveUrl?: string;
  githubUrl?: string;
  featured?: boolean;
  order?: number;
};

export type Profile = {
  _id: string;
  _type: "profile";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  firstName?: string;
  lastName?: string;
  headline?: string;
  headlineStaticText?: string;
  headlineAnimatedWords?: Array<string>;
  headlineAnimationDuration?: number;
  shortBio?: string;
  fullBio?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  profileImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  email?: string;
  phone?: string;
  location?: string;
  availability?: "available" | "open" | "unavailable";
  socialLinks?: {
    github?: string;
    linkedin?: string;
    twitter?: string;
    website?: string;
    medium?: string;
    devto?: string;
    youtube?: string;
    stackoverflow?: string;
  };
  yearsOfExperience?: number;
  stats?: Array<{
    label?: string;
    value?: string;
    _key: string;
  }>;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes = Navigation | SiteSettings | SanityImageCrop | SanityImageHotspot | Blog | Slug | Achievement | Certification | Education | Experience | Skill | Project | Profile | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageMetadata | SanityFileAsset | SanityAssetSourceData | SanityImageAsset | Geopoint;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./src/components/sections/AboutSection.tsx
// Variable: ABOUT_QUERY
// Query: coalesce(    *[_type == "profile" && _id == "singleton-profile"][0],    *[_type == "profile"][0]  ){    firstName,    lastName,    fullBio,    yearsOfExperience,    stats,    email,    phone,    location  }
export type ABOUT_QUERYResult = {
  firstName: string | null;
  lastName: string | null;
  fullBio: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  yearsOfExperience: number | null;
  stats: Array<{
    label?: string;
    value?: string;
    _key: string;
  }> | null;
  email: string | null;
  phone: string | null;
  location: string | null;
} | null;

// Source: ./src/components/sections/AchievementsSection.tsx
// Variable: ACHIEVEMENTS_SECTION_QUERY
// Query: *[_type == "achievement"] | order(featured desc, date desc){    _id, title, description, date, type, issuer, featured, url  }
export type ACHIEVEMENTS_SECTION_QUERYResult = Array<{
  _id: string;
  title: string | null;
  description: string | null;
  date: string | null;
  type: "award" | "entrepreneurship" | "experience" | "hackathon" | "leadership" | "milestone" | "open-source" | "other" | "publication" | "recognition" | "speaking" | "sports" | null;
  issuer: string | null;
  featured: boolean | null;
  url: string | null;
}>;

// Source: ./src/components/sections/BlogSection.tsx
// Variable: BLOG_SECTION_QUERY
// Query: *[_type == "blog"] | order(publishedAt desc)[0...6]{    _id, title, slug, excerpt, externalUrl, publishedAt, readTime, category  }
export type BLOG_SECTION_QUERYResult = Array<{
  _id: string;
  title: string | null;
  slug: Slug | null;
  excerpt: string | null;
  externalUrl: string | null;
  publishedAt: string | null;
  readTime: number | null;
  category: string | null;
}>;

// Source: ./src/components/sections/CertificationsSection.tsx
// Variable: CERTS_SECTION_QUERY
// Query: *[_type == "certification"] | order(issueDate desc){    _id, name, issuer, issueDate, expiryDate, credentialId, credentialUrl, logo, description,    skills[]->{ _id, name, category, color }  }
export type CERTS_SECTION_QUERYResult = Array<{
  _id: string;
  name: string | null;
  issuer: string | null;
  issueDate: string | null;
  expiryDate: string | null;
  credentialId: string | null;
  credentialUrl: string | null;
  logo: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  description: string | null;
  skills: Array<{
    _id: string;
    name: string | null;
    category: "ai-ml" | "backend" | "cloud" | "database" | "design" | "devops" | "frontend" | "mobile" | "other" | "soft-skills" | "testing" | "tools" | null;
    color: "amber" | "cyan" | "emerald" | "orange" | "pink" | "sky" | "slate" | "violet" | null;
  }> | null;
}>;

// Source: ./src/components/sections/ContactSection.tsx
// Variable: CONTACT_QUERY
// Query: coalesce(    *[_type == "profile" && _id == "singleton-profile"][0],    *[_type == "profile"][0]  ){    email,    location,    socialLinks{      github,      linkedin,      twitter,      website    }  }
export type CONTACT_QUERYResult = {
  email: string | null;
  location: string | null;
  socialLinks: {
    github: string | null;
    linkedin: string | null;
    twitter: string | null;
    website: string | null;
  } | null;
} | null;

// Source: ./src/components/sections/EducationSection.tsx
// Variable: EDUCATION_SECTION_QUERY
// Query: *[_type == "education"] | order(startDate desc){    _id, institution, degree, fieldOfStudy, startDate, endDate, current, description, gpa, logo  }
export type EDUCATION_SECTION_QUERYResult = Array<{
  _id: string;
  institution: string | null;
  degree: string | null;
  fieldOfStudy: string | null;
  startDate: string | null;
  endDate: string | null;
  current: boolean | null;
  description: string | null;
  gpa: string | null;
  logo: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
}>;

// Source: ./src/sanity/lib/queries.ts
// Variable: PROFILE_QUERY
// Query: coalesce(  *[_type == "profile" && _id == "singleton-profile"][0],  *[_type == "profile"][0]){  _id,  firstName,  lastName,  headline,  headlineStaticText,  headlineAnimatedWords,  headlineAnimationDuration,  shortBio,  fullBio,  profileImage,  email,  phone,  location,  availability,  socialLinks{    github,    linkedin,    twitter,    website,    medium,    devto,    youtube,    stackoverflow  },  yearsOfExperience,  stats[]{    label,    value  }}
export type PROFILE_QUERYResult = {
  _id: string;
  firstName: string | null;
  lastName: string | null;
  headline: string | null;
  headlineStaticText: string | null;
  headlineAnimatedWords: Array<string> | null;
  headlineAnimationDuration: number | null;
  shortBio: string | null;
  fullBio: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  profileImage: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  email: string | null;
  phone: string | null;
  location: string | null;
  availability: "available" | "open" | "unavailable" | null;
  socialLinks: {
    github: string | null;
    linkedin: string | null;
    twitter: string | null;
    website: string | null;
    medium: string | null;
    devto: string | null;
    youtube: string | null;
    stackoverflow: string | null;
  } | null;
  yearsOfExperience: number | null;
  stats: Array<{
    label: string | null;
    value: string | null;
  }> | null;
} | {
  _id: "singleton-profile";
  firstName: string | null;
  lastName: string | null;
  headline: string | null;
  headlineStaticText: string | null;
  headlineAnimatedWords: Array<string> | null;
  headlineAnimationDuration: number | null;
  shortBio: string | null;
  fullBio: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  profileImage: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  email: string | null;
  phone: string | null;
  location: string | null;
  availability: "available" | "open" | "unavailable" | null;
  socialLinks: {
    github: string | null;
    linkedin: string | null;
    twitter: string | null;
    website: string | null;
    medium: string | null;
    devto: string | null;
    youtube: string | null;
    stackoverflow: string | null;
  } | null;
  yearsOfExperience: number | null;
  stats: Array<{
    label: string | null;
    value: string | null;
  }> | null;
} | null;
// Variable: SITE_SETTINGS_QUERY
// Query: coalesce(  *[_type == "siteSettings" && _id == "singleton-site-settings"][0],  *[_type == "siteSettings" && _id == "singleton-siteSettings"][0],  *[_type == "siteSettings"][0]){  _id,  siteTitle,  siteDescription,  siteLogo,  showBlog,  _createdAt,  _updatedAt}
export type SITE_SETTINGS_QUERYResult = {
  _id: string;
  siteTitle: string | null;
  siteDescription: string | null;
  siteLogo: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  showBlog: boolean | null;
  _createdAt: string;
  _updatedAt: string;
} | {
  _id: "singleton-site-settings";
  siteTitle: string | null;
  siteDescription: string | null;
  siteLogo: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  showBlog: boolean | null;
  _createdAt: string;
  _updatedAt: string;
} | {
  _id: "singleton-siteSettings";
  siteTitle: string | null;
  siteDescription: string | null;
  siteLogo: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  showBlog: boolean | null;
  _createdAt: string;
  _updatedAt: string;
} | null;
// Variable: NAVIGATION_QUERY
// Query: *[_type == "navigation"] | order(order asc){  _id,  title,  href,  icon,  "isExternal": select(    isExternal == true => true,    linkType == "external" => true,    false  ),  order}
export type NAVIGATION_QUERYResult = Array<{
  _id: string;
  title: string | null;
  href: string | null;
  icon: string | null;
  isExternal: false | true;
  order: number | null;
}>;
// Variable: PROJECTS_QUERY
// Query: *[_type == "project"] | order(order asc, title asc){  _id,  title,  slug{ current },  tagline,  summary,  coverImage,  technologies[]->{    _id,    name,    category,    proficiency,    percentage,    yearsOfExperience,    tone,    color  },  category,  liveUrl,  githubUrl,  "featured": coalesce(featured, false),  order}
export type PROJECTS_QUERYResult = Array<{
  _id: string;
  title: string | null;
  slug: {
    current: string | null;
  } | null;
  tagline: string | null;
  summary: string | null;
  coverImage: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  technologies: Array<{
    _id: string;
    name: string | null;
    category: "ai-ml" | "backend" | "cloud" | "database" | "design" | "devops" | "frontend" | "mobile" | "other" | "soft-skills" | "testing" | "tools" | null;
    proficiency: "advanced" | "beginner" | "expert" | "intermediate" | null;
    percentage: number | null;
    yearsOfExperience: number | null;
    tone: "accent" | "highlight" | "muted" | "neutral" | null;
    color: "amber" | "cyan" | "emerald" | "orange" | "pink" | "sky" | "slate" | "violet" | null;
  }> | null;
  category: "ai-ml" | "api-backend" | "browser-extension" | "cli-tool" | "desktop-app" | "devops" | "game" | "mobile-app" | "open-source" | "other" | "web-app" | null;
  liveUrl: string | null;
  githubUrl: string | null;
  featured: boolean | false;
  order: number | null;
}>;
// Variable: SKILLS_QUERY
// Query: *[_type == "skill"] | order(category asc, name asc){  _id,  name,  category,  proficiency,  percentage,  yearsOfExperience,  "tone": coalesce(tone, "neutral"),  color}
export type SKILLS_QUERYResult = Array<{
  _id: string;
  name: string | null;
  category: "ai-ml" | "backend" | "cloud" | "database" | "design" | "devops" | "frontend" | "mobile" | "other" | "soft-skills" | "testing" | "tools" | null;
  proficiency: "advanced" | "beginner" | "expert" | "intermediate" | null;
  percentage: number | null;
  yearsOfExperience: number | null;
  tone: "accent" | "highlight" | "muted" | "neutral";
  color: "amber" | "cyan" | "emerald" | "orange" | "pink" | "sky" | "slate" | "violet" | null;
}>;
// Variable: EXPERIENCE_QUERY
// Query: *[_type == "experience"] | order(order asc, startDate desc){  _id,  company,  position,  employmentType,  location,  startDate,  endDate,  "current": select(    defined(tenure) => tenure == "current",    current == true => true,    false  ),  "tenure": select(    defined(tenure) => tenure,    current == true => "current",    "past"  ),  description,  responsibilities[],  achievements[],  technologies[]->{    _id,    name,    category,    proficiency,    percentage,    yearsOfExperience,    tone,    color  },  companyLogo,  companyWebsite,  order}
export type EXPERIENCE_QUERYResult = Array<{
  _id: string;
  company: string | null;
  position: string | null;
  employmentType: "contract" | "freelance" | "full-time" | "internship" | "part-time" | null;
  location: string | null;
  startDate: string | null;
  endDate: string | null;
  current: false | true;
  tenure: "current" | "past";
  description: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  responsibilities: Array<string> | null;
  achievements: Array<string> | null;
  technologies: Array<{
    _id: string;
    name: string | null;
    category: "ai-ml" | "backend" | "cloud" | "database" | "design" | "devops" | "frontend" | "mobile" | "other" | "soft-skills" | "testing" | "tools" | null;
    proficiency: "advanced" | "beginner" | "expert" | "intermediate" | null;
    percentage: number | null;
    yearsOfExperience: number | null;
    tone: "accent" | "highlight" | "muted" | "neutral" | null;
    color: "amber" | "cyan" | "emerald" | "orange" | "pink" | "sky" | "slate" | "violet" | null;
  }> | null;
  companyLogo: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  companyWebsite: string | null;
  order: number | null;
}>;
// Variable: EDUCATION_QUERY
// Query: *[_type == "education"] | order(startDate desc){    _id, institution, degree, fieldOfStudy, startDate, endDate, current, description, gpa, logo  }
export type EDUCATION_QUERYResult = Array<{
  _id: string;
  institution: string | null;
  degree: string | null;
  fieldOfStudy: string | null;
  startDate: string | null;
  endDate: string | null;
  current: boolean | null;
  description: string | null;
  gpa: string | null;
  logo: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
}>;
// Variable: CERTIFICATIONS_QUERY
// Query: *[_type == "certification"] | order(issueDate desc){    _id, name, issuer, issueDate, credentialId, credentialUrl, logo, description  }
export type CERTIFICATIONS_QUERYResult = Array<{
  _id: string;
  name: string | null;
  issuer: string | null;
  issueDate: string | null;
  credentialId: string | null;
  credentialUrl: string | null;
  logo: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  description: string | null;
}>;
// Variable: ACHIEVEMENTS_QUERY
// Query: *[_type == "achievement"] | order(featured desc, order asc, date desc){    _id, title, description, date, type, featured, url  }
export type ACHIEVEMENTS_QUERYResult = Array<{
  _id: string;
  title: string | null;
  description: string | null;
  date: string | null;
  type: "award" | "entrepreneurship" | "experience" | "hackathon" | "leadership" | "milestone" | "open-source" | "other" | "publication" | "recognition" | "speaking" | "sports" | null;
  featured: boolean | null;
  url: string | null;
}>;
// Variable: BLOG_QUERY
// Query: *[_type == "blog"] | order(publishedAt desc)[0...6]{    _id, title, slug, excerpt, externalUrl, publishedAt, readTime, category, featuredImage  }
export type BLOG_QUERYResult = Array<{
  _id: string;
  title: string | null;
  slug: Slug | null;
  excerpt: string | null;
  externalUrl: string | null;
  publishedAt: string | null;
  readTime: number | null;
  category: string | null;
  featuredImage: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
}>;
// Variable: PROJECT_BY_SLUG_QUERY
// Query: *[_type == "project" && slug.current == $slug][0]{    _id, title, "slug": slug.current, tagline, summary,    "technologies": technologies[]->{ name },    liveUrl, githubUrl  }
export type PROJECT_BY_SLUG_QUERYResult = {
  _id: string;
  title: string | null;
  slug: string | null;
  tagline: string | null;
  summary: string | null;
  technologies: Array<{
    name: string | null;
  }> | null;
  liveUrl: string | null;
  githubUrl: string | null;
} | null;
// Variable: EXPERIENCE_BY_ID_QUERY
// Query: *[_type == "experience" && _id == $id][0]{    _id, company, position, employmentType, location,    startDate, endDate, current, description,    responsibilities, "technologies": technologies[]->{ name }  }
export type EXPERIENCE_BY_ID_QUERYResult = {
  _id: string;
  company: string | null;
  position: string | null;
  employmentType: "contract" | "freelance" | "full-time" | "internship" | "part-time" | null;
  location: string | null;
  startDate: string | null;
  endDate: string | null;
  current: null;
  description: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  responsibilities: Array<string> | null;
  technologies: Array<{
    name: string | null;
  }> | null;
} | null;
// Variable: CHAT_CATALOG_QUERY
// Query: {  "projects": *[_type == "project"] | order(order asc, title asc){    _id, title, "slug": slug.current, tagline  },  "experience": *[_type == "experience"] | order(order asc, startDate desc){    _id, company, position,    "current": select(current == true => true, tenure == "current" => true, false),    description  },  "skills": *[_type == "skill"] | order(category asc, name asc){    _id, name, category, proficiency  },  "education": *[_type == "education"] | order(startDate desc){    _id, institution, degree, fieldOfStudy, startDate, endDate  },  "certifications": *[_type == "certification"] | order(issueDate desc){    _id, name, issuer, issueDate  },  "achievements": *[_type == "achievement"] | order(featured desc, order asc){    _id, title, description, date, type, featured  }}
export type CHAT_CATALOG_QUERYResult = {
  projects: Array<{
    _id: string;
    title: string | null;
    slug: string | null;
    tagline: string | null;
  }>;
  experience: Array<{
    _id: string;
    company: string | null;
    position: string | null;
    current: false | true;
    description: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }> | null;
  }>;
  skills: Array<{
    _id: string;
    name: string | null;
    category: "ai-ml" | "backend" | "cloud" | "database" | "design" | "devops" | "frontend" | "mobile" | "other" | "soft-skills" | "testing" | "tools" | null;
    proficiency: "advanced" | "beginner" | "expert" | "intermediate" | null;
  }>;
  education: Array<{
    _id: string;
    institution: string | null;
    degree: string | null;
    fieldOfStudy: string | null;
    startDate: string | null;
    endDate: string | null;
  }>;
  certifications: Array<{
    _id: string;
    name: string | null;
    issuer: string | null;
    issueDate: string | null;
  }>;
  achievements: Array<{
    _id: string;
    title: string | null;
    description: string | null;
    date: string | null;
    type: "award" | "entrepreneurship" | "experience" | "hackathon" | "leadership" | "milestone" | "open-source" | "other" | "publication" | "recognition" | "speaking" | "sports" | null;
    featured: boolean | null;
  }>;
};

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "\n  coalesce(\n    *[_type == \"profile\" && _id == \"singleton-profile\"][0],\n    *[_type == \"profile\"][0]\n  ){\n    firstName,\n    lastName,\n    fullBio,\n    yearsOfExperience,\n    stats,\n    email,\n    phone,\n    location\n  }\n": ABOUT_QUERYResult;
    "\n  *[_type == \"achievement\"] | order(featured desc, date desc){\n    _id, title, description, date, type, issuer, featured, url\n  }\n": ACHIEVEMENTS_SECTION_QUERYResult;
    "\n  *[_type == \"blog\"] | order(publishedAt desc)[0...6]{\n    _id, title, slug, excerpt, externalUrl, publishedAt, readTime, category\n  }\n": BLOG_SECTION_QUERYResult;
    "\n  *[_type == \"certification\"] | order(issueDate desc){\n    _id, name, issuer, issueDate, expiryDate, credentialId, credentialUrl, logo, description,\n    skills[]->{ _id, name, category, color }\n  }\n": CERTS_SECTION_QUERYResult;
    "\n  coalesce(\n    *[_type == \"profile\" && _id == \"singleton-profile\"][0],\n    *[_type == \"profile\"][0]\n  ){\n    email,\n    location,\n    socialLinks{\n      github,\n      linkedin,\n      twitter,\n      website\n    }\n  }\n": CONTACT_QUERYResult;
    "\n  *[_type == \"education\"] | order(startDate desc){\n    _id, institution, degree, fieldOfStudy, startDate, endDate, current, description, gpa, logo\n  }\n": EDUCATION_SECTION_QUERYResult | EDUCATION_QUERYResult;
    "\ncoalesce(\n  *[_type == \"profile\" && _id == \"singleton-profile\"][0],\n  *[_type == \"profile\"][0]\n){\n  _id,\n  firstName,\n  lastName,\n  headline,\n  headlineStaticText,\n  headlineAnimatedWords,\n  headlineAnimationDuration,\n  shortBio,\n  fullBio,\n  profileImage,\n  email,\n  phone,\n  location,\n  availability,\n  socialLinks{\n    github,\n    linkedin,\n    twitter,\n    website,\n    medium,\n    devto,\n    youtube,\n    stackoverflow\n  },\n  yearsOfExperience,\n  stats[]{\n    label,\n    value\n  }\n}\n": PROFILE_QUERYResult;
    "\ncoalesce(\n  *[_type == \"siteSettings\" && _id == \"singleton-site-settings\"][0],\n  *[_type == \"siteSettings\" && _id == \"singleton-siteSettings\"][0],\n  *[_type == \"siteSettings\"][0]\n){\n  _id,\n  siteTitle,\n  siteDescription,\n  siteLogo,\n  showBlog,\n  _createdAt,\n  _updatedAt\n}\n": SITE_SETTINGS_QUERYResult;
    "\n*[_type == \"navigation\"] | order(order asc){\n  _id,\n  title,\n  href,\n  icon,\n  \"isExternal\": select(\n    isExternal == true => true,\n    linkType == \"external\" => true,\n    false\n  ),\n  order\n}\n": NAVIGATION_QUERYResult;
    "\n*[_type == \"project\"] | order(order asc, title asc){\n  _id,\n  title,\n  slug{ current },\n  tagline,\n  summary,\n  coverImage,\n  technologies[]->{\n    _id,\n    name,\n    category,\n    proficiency,\n    percentage,\n    yearsOfExperience,\n    tone,\n    color\n  },\n  category,\n  liveUrl,\n  githubUrl,\n  \"featured\": coalesce(featured, false),\n  order\n}\n": PROJECTS_QUERYResult;
    "\n*[_type == \"skill\"] | order(category asc, name asc){\n  _id,\n  name,\n  category,\n  proficiency,\n  percentage,\n  yearsOfExperience,\n  \"tone\": coalesce(tone, \"neutral\"),\n  color\n}\n": SKILLS_QUERYResult;
    "\n*[_type == \"experience\"] | order(order asc, startDate desc){\n  _id,\n  company,\n  position,\n  employmentType,\n  location,\n  startDate,\n  endDate,\n  \"current\": select(\n    defined(tenure) => tenure == \"current\",\n    current == true => true,\n    false\n  ),\n  \"tenure\": select(\n    defined(tenure) => tenure,\n    current == true => \"current\",\n    \"past\"\n  ),\n  description,\n  responsibilities[],\n  achievements[],\n  technologies[]->{\n    _id,\n    name,\n    category,\n    proficiency,\n    percentage,\n    yearsOfExperience,\n    tone,\n    color\n  },\n  companyLogo,\n  companyWebsite,\n  order\n}\n": EXPERIENCE_QUERYResult;
    "\n  *[_type == \"certification\"] | order(issueDate desc){\n    _id, name, issuer, issueDate, credentialId, credentialUrl, logo, description\n  }\n": CERTIFICATIONS_QUERYResult;
    "\n  *[_type == \"achievement\"] | order(featured desc, order asc, date desc){\n    _id, title, description, date, type, featured, url\n  }\n": ACHIEVEMENTS_QUERYResult;
    "\n  *[_type == \"blog\"] | order(publishedAt desc)[0...6]{\n    _id, title, slug, excerpt, externalUrl, publishedAt, readTime, category, featuredImage\n  }\n": BLOG_QUERYResult;
    "\n  *[_type == \"project\" && slug.current == $slug][0]{\n    _id, title, \"slug\": slug.current, tagline, summary,\n    \"technologies\": technologies[]->{ name },\n    liveUrl, githubUrl\n  }\n": PROJECT_BY_SLUG_QUERYResult;
    "\n  *[_type == \"experience\" && _id == $id][0]{\n    _id, company, position, employmentType, location,\n    startDate, endDate, current, description,\n    responsibilities, \"technologies\": technologies[]->{ name }\n  }\n": EXPERIENCE_BY_ID_QUERYResult;
    "{\n  \"projects\": *[_type == \"project\"] | order(order asc, title asc){\n    _id, title, \"slug\": slug.current, tagline\n  },\n  \"experience\": *[_type == \"experience\"] | order(order asc, startDate desc){\n    _id, company, position,\n    \"current\": select(current == true => true, tenure == \"current\" => true, false),\n    description\n  },\n  \"skills\": *[_type == \"skill\"] | order(category asc, name asc){\n    _id, name, category, proficiency\n  },\n  \"education\": *[_type == \"education\"] | order(startDate desc){\n    _id, institution, degree, fieldOfStudy, startDate, endDate\n  },\n  \"certifications\": *[_type == \"certification\"] | order(issueDate desc){\n    _id, name, issuer, issueDate\n  },\n  \"achievements\": *[_type == \"achievement\"] | order(featured desc, order asc){\n    _id, title, description, date, type, featured\n  }\n}": CHAT_CATALOG_QUERYResult;
  }
}
